# Java rules adapted from Fluent Bit v5.1.3 flb_ml_parser_java.c.
# Copyright (C) 2015-2026 The Fluent Bit Authors. Apache-2.0;
# see vendor/FLUENT-BIT-LICENSE. Modification: group Docker stdout/stderr.
# Tail already decoded Docker JSON, so no sub-parser belongs here.
[MULTILINE_PARSER]
    Name           krate_java
    Type           regex
    Flush_Timeout  2000
    Key_Content    log
    Key_Group      stream
    Rule "start_state, java_start_exception" "/(.)(?:Exception|Error|Throwable|V8 errors stack trace)[:\r\n]/" "java_after_exception"
    Rule "java_after_exception" "/^[\t ]*nested exception is:[\t ]*/" "java_start_exception"
    Rule "java_after_exception" "/^[\r\n]*$/" "java_after_exception"
    Rule "java_after_exception, java" "/^[\t ]+(?:eval )?at /" "java"
    Rule "java_after_exception, java" "/^[\t ]+--- End of inner exception stack trace ---$/" "java"
    Rule "java_after_exception, java" "/^--- End of stack trace from previous location where exception was thrown ---$/" "java"
    Rule "java_after_exception, java" "/^[\t ]*(?:Caused by|Suppressed):/" "java_after_exception"
    Rule "java_after_exception, java" "/^[\t ]*... \d+ (?:more|common frames omitted)/" "java"
