#!/usr/bin/env python3
"""Render the per-install configuration of the parallel monitoring services.

Runs as the one-shot monitoring-init service before Perses, its gateway,
OAuth2 Proxy, the access guard and Alertmanager start. Inputs are the
environment (monitoring/.env) and, for SSO, the site settings generated by
`sso/configure.py --app perses`. Each output is written into the volume of
the service that reads it, owned by that service's user, so no secret is
stored on the host outside .env.
"""
import json
import os
from pathlib import Path
import re
import shutil
import sys
from urllib.parse import urlsplit

PERSES_UID = 65532       # persesdev/perses and oauth2-proxy run as nonroot
ALERTMANAGER_UID = 65534  # prom/alertmanager runs as nobody
SYNC_UID = 65534
GROUP = re.compile(r'[^,\s"\'\\]{1,256}')
NAME = re.compile(r'[A-Za-z0-9][A-Za-z0-9_.-]{0,127}')
EMAIL = re.compile(r'[^@\s,;"]+@[^@\s,;"]+')


class ConfigError(ValueError):
    pass


def require(env, key):
    value = env.get(key, '')
    if not value:
        raise ConfigError(key + ' must be set in monitoring/.env')
    return value


def flag(env, key, default=False):
    value = env.get(key, '').strip().lower()
    if not value:
        return default
    if value in ('1', 'true', 'yes', 'on'):
        return True
    if value in ('0', 'false', 'no', 'off'):
        return False
    raise ConfigError(key + ' must be true or false')


def https_url(value, key):
    parts = urlsplit(value)
    if parts.scheme != 'https' or not parts.hostname or parts.query or parts.fragment:
        raise ConfigError(key + ' must be an https:// URL without query or fragment')
    return value.rstrip('/')


def site_settings(path, mode):
    try:
        site = json.loads(Path(path).read_text())
    except FileNotFoundError:
        raise ConfigError('PERSES_AUTH_MODE=%s needs %s; generate it with sso/configure.py --app perses' % (mode, path))
    for key in ('issuer', 'client_id', 'viewer_group', 'admin_group', 'groups_claim', 'public_url'):
        if not isinstance(site.get(key), str) or not site[key]:
            raise ConfigError('site settings: ' + key + ' is required')
    https_url(site['issuer'], 'issuer')
    https_url(site['public_url'], 'public_url')
    for key in ('viewer_group', 'admin_group'):
        if not GROUP.fullmatch(site[key]):
            raise ConfigError('site settings: ' + key + ' must not contain commas, quotes or whitespace')
    if site['viewer_group'] == site['admin_group']:
        raise ConfigError('site settings: viewer_group and admin_group must differ')
    if mode == 'native' and not NAME.fullmatch(site.get('service_client_id', '')):
        raise ConfigError('site settings: service_client_id must be a valid Perses user name')
    return site


def yaml_string(value):
    return json.dumps(value)


def perses_config(mode, site):
    lines = [
        '# Rendered by monitoring/render.py; do not edit.',
        'security:',
        '  readonly: false',
        '  enable_auth: %s' % ('false' if mode == 'gateway' else 'true'),
        '  encryption_key_file: /etc/krate/perses/rendered/encryption.key',
        '  cookie:',
        '    same_site: lax',
        '    secure: true',
    ]
    if mode != 'gateway':
        lines += [
            '  authentication:',
            '    access_token_ttl: 15m',
            '    refresh_token_ttl: 24h',
            '    disable_sign_up: true',
            '    providers:',
            '      enable_native: %s' % ('true' if mode == 'local' else 'false'),
        ]
        if mode == 'native':
            lines += [
                '      oidc:',
                '        - slug_id: krate',
                '          name: %s' % yaml_string(site.get('display_name', 'Company sign-in')),
                '          client_id: %s' % yaml_string(site['client_id']),
                '          client_secret_file: /etc/krate/perses/rendered/oidc-client-secret',
                '          issuer: %s' % yaml_string(site['issuer']),
                '          redirect_uri: %s' % yaml_string(site['public_url'] + '/api/auth/providers/oidc/krate/callback'),
                '          scopes: %s' % json.dumps(site.get('scopes', ['openid', 'profile', 'email'])),
            ]
        lines += [
            '  authorization:',
            '    provider:',
            '      native:',
            '        enable: true',
            '        guest_permissions: []',
        ]
    lines += [
        'database:',
        '  file:',
        '    folder: /perses/data',
        '    extension: json',
        'provisioning:',
        '  interval: 10m',
        '  folders:',
        '    - /etc/krate/perses/provisioning',
        '    - /etc/krate/perses/rendered/provisioning',
        'plugin:',
        '  enable_dev: false',
        'frontend:',
        '  important_dashboards:',
        '    - project: krate',
        '      dashboard: krate-overview',
        '  information: "Krate monitoring: Kafka metrics from Prometheus, container logs from VictoriaLogs."',
    ]
    return '\n'.join(lines) + '\n'


def perses_provisioning(mode, env, site):
    if mode == 'local':
        user = require(env, 'PERSES_ADMIN_USER')
        password = require(env, 'PERSES_ADMIN_PASSWORD')
        if not NAME.fullmatch(user):
            raise ConfigError('PERSES_ADMIN_USER must be a valid Perses user name')
        if len(password) < 12 or password in ('changeme', 'REPLACE_ME'):
            raise ConfigError('PERSES_ADMIN_PASSWORD must be at least 12 characters and not a placeholder')
        return [
            {'kind': 'User', 'metadata': {'name': user}, 'spec': {'nativeProvider': {'password': password}}},
            {'kind': 'GlobalRoleBinding', 'metadata': {'name': 'krate-local-admin'},
             'spec': {'role': 'krate-admin', 'subjects': [{'kind': 'User', 'name': user}]}},
        ]
    if mode == 'native':
        return [{'kind': 'GlobalRoleBinding', 'metadata': {'name': 'krate-sync'},
                 'spec': {'role': 'krate-sync', 'subjects': [{'kind': 'User', 'name': site['service_client_id']}]}}]
    return []


def oauth2_proxy_config(site, env):
    public = site['public_url']
    host = urlsplit(public).netloc
    minutes = int(site.get('group_proof_minutes', 15))
    if not 1 <= minutes <= 60:
        raise ConfigError('site settings: group_proof_minutes must be between 1 and 60')
    hours = int(site.get('session_hours', 8))
    if not 1 <= hours <= 24:
        raise ConfigError('site settings: session_hours must be between 1 and 24')
    scopes = ' '.join(site.get('scopes', ['openid', 'profile', 'email']))
    settings = {
        'provider': 'oidc',
        'oidc_issuer_url': site['issuer'],
        'client_id': site['client_id'],
        'redirect_url': public + '/oauth2/callback',
        'http_address': '0.0.0.0:4180',
        'reverse_proxy': True,
        # Only the gateway reaches OAuth2 Proxy (no host port), over a private network.
        'trusted_proxy_ips': ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'],
        'email_domains': ['*'],
        'scope': scopes,
        'oidc_groups_claim': site['groups_claim'],
        'allowed_groups': [site['viewer_group'], site['admin_group']],
        'skip_provider_button': True,
        'code_challenge_method': 'S256',
        'insecure_oidc_skip_nonce': False,
        'cookie_name': '_oauth2_proxy',
        'cookie_secure': True,
        'cookie_httponly': True,
        'cookie_samesite': 'lax',
        # The session proves current group membership. It is refreshed with the
        # IdP every group_proof_minutes, which brings current groups; an
        # invalid_grant (revoked or ended IdP session) clears it, and a session
        # whose refresh keeps failing is rejected once its token expires.
        'cookie_expire': '%dh' % hours,
        'cookie_refresh': '%dm' % minutes,
        'session_store_type': 'cookie',
        'set_xauthrequest': True,
        'upstreams': ['static://202'],
        'whitelist_domains': [host],
        'skip_auth_routes': [],
    }
    lines = ['# Rendered by monitoring/render.py; do not edit. Secrets come from the environment.']
    for key, value in settings.items():
        lines.append('%s = %s' % (key, json.dumps(value)))
    return '\n'.join(lines) + '\n'


def sync_config(mode, site):
    config = {
        'mode': mode, 'issuer': site['issuer'], 'viewer_group': site['viewer_group'],
        'admin_group': site['admin_group'], 'oidc_slug': 'krate',
        'perses_url': 'http://perses:8080', 'oauth2_proxy_url': 'http://oauth2-proxy:4180',
        'listen_port': 9091, 'verify_ttl': 30,
        # A user not seen with a current IdP proof for one proof period plus a
        # margin loses their grants; the next authenticated request restores them.
        'grant_ttl': int(site.get('group_proof_minutes', 15)) * 60 + 120,
    }
    if mode == 'native':
        config.update({'service_client_id': site['service_client_id'],
                       'service_client_secret_file': '/etc/krate/perses-sync/rendered/service-client-secret',
                       'service_binding': 'krate-sync', 'state_file': '/var/lib/krate-perses-sync/ledger.json'})
    return json.dumps(config, indent=2) + '\n'


GATEWAY_COMMON = '''# Rendered by monitoring/render.py; do not edit.
server {
    listen 80;
    server_name _;
    return 301 https://$host:%(port)s$request_uri;
}
server {
    listen 3443 ssl;
    server_name _;
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 8m;
    # OAuth2 Proxy keeps its session in cookies; responses and requests carry
    # them, so the default 4k/8k header buffers are too small.
    large_client_header_buffers 8 32k;
    proxy_buffer_size 32k;
    proxy_buffers 8 32k;
    proxy_busy_buffers_size 64k;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;
    add_header Strict-Transport-Security "max-age=31536000" always;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    # Resolve upstreams per request, so the gateway starts before them.
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $krate_perses http://perses:8080;
    # Krate's viewer UI script (hides write controls Perses would show).
    location = /krate/ui.js {
        alias /etc/krate/perses-gateway/krate-ui.js;
        default_type application/javascript;
        add_header Cache-Control "no-cache" always;
        add_header X-Content-Type-Options nosniff always;
    }
'''

GATEWAY_INJECT = '''        # Inject the viewer UI script into Perses' HTML (uncompressed for sub_filter).
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<script src="/krate/ui.js"></script></head>';
        sub_filter_once on;
'''

GATEWAY_LOCAL = '''    location = /api/auth/providers/native/login {
        limit_req zone=krate_perses_login burst=10 nodelay;
        proxy_pass $krate_perses;
    }
    # Service and device-code token routes are not used and stay closed.
    location ~ ^/api/auth/providers/(oidc|oauth)/ {
        return 404;
    }
    # Local mode has only the provisioned admin.
    location = /krate/role {
        default_type text/plain;
        add_header Cache-Control "no-store" always;
        return 200 'admin';
    }
    location / {
%(inject)s        proxy_pass $krate_perses;
        proxy_http_version 1.1;
        proxy_read_timeout 300s;
    }
}
'''

GATEWAY_SSO = '''    set $krate_oauth2 http://oauth2-proxy:4180;
    set $krate_sync http://perses-sync:9091;
    location /oauth2/ {
        limit_req zone=krate_perses_login burst=20 nodelay;
        proxy_pass $krate_oauth2;
    }
    location = /oauth2/auth {
        return 404;
    }
    location = /_krate_guard {
        internal;
        proxy_pass $krate_sync/guard;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }
    location = /api/auth/refresh {
        proxy_pass $krate_sync/refresh;
    }
    # The current role from the guard (same IdP groups the server enforces).
    # Not 'return' + auth_request: return runs before the access phase.
    location = /krate/role {
        proxy_pass $krate_sync/role;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie;
        add_header Cache-Control "no-store" always;
    }
    location @krate_signin {
        if ($krate_browser) {
            return 302 /oauth2/start?rd=$krate_return;
        }
        return 401;
    }
    location / {
        auth_request /_krate_guard;
        error_page 401 = @krate_signin;
        # Relay OAuth2 Proxy's refreshed session cookies (it may split them).
        auth_request_set $krate_cookie_0 $upstream_http_x_krate_set_cookie_0;
        auth_request_set $krate_cookie_1 $upstream_http_x_krate_set_cookie_1;
        auth_request_set $krate_cookie_2 $upstream_http_x_krate_set_cookie_2;
        auth_request_set $krate_cookie_3 $upstream_http_x_krate_set_cookie_3;
        add_header Set-Cookie $krate_cookie_0 always;
        add_header Set-Cookie $krate_cookie_1 always;
        add_header Set-Cookie $krate_cookie_2 always;
        add_header Set-Cookie $krate_cookie_3 always;
        # add_header here stops inheritance from the server block, so repeat them.
        add_header X-Frame-Options SAMEORIGIN always;
        add_header X-Content-Type-Options nosniff always;
        add_header Referrer-Policy no-referrer always;
        add_header Strict-Transport-Security "max-age=31536000" always;
%(inject)s        proxy_pass $krate_perses;
        proxy_http_version 1.1;
        proxy_read_timeout 300s;
    }
}
'''

GATEWAY_HTTP = '''limit_req_zone $binary_remote_addr zone=krate_perses_login:10m rate=5r/s;
map $http_accept $krate_browser {
    default 0;
    "~*text/html" 1;
}
map $request_uri $krate_return {
    default $request_uri;
    "~^/oauth2/" /;
}
'''


def gateway_config(mode, env):
    port = env.get('PERSES_PORT', '3443')
    if not port.isdigit():
        raise ConfigError('PERSES_PORT must be a port number')
    body = (GATEWAY_LOCAL if mode == 'local' else GATEWAY_SSO) % {'inject': GATEWAY_INJECT}
    return GATEWAY_HTTP + GATEWAY_COMMON % {'port': port} + body


def alertmanager_config(env):
    enabled = flag(env, 'ALERTMANAGER_EMAIL_ENABLED', flag(env, 'GF_SMTP_ENABLED'))
    lines = ['# Rendered by monitoring/render.py; do not edit.']
    if enabled:
        smarthost = require(env, 'GF_SMTP_HOST')
        if not re.fullmatch(r'[A-Za-z0-9.-]+:\d{1,5}', smarthost):
            raise ConfigError('GF_SMTP_HOST must be host:port')
        sender = require(env, 'GF_SMTP_FROM_ADDRESS')
        recipients = [r.strip() for r in re.split(r'[;,]', require(env, 'ALERT_EMAIL_TO')) if r.strip()]
        if not EMAIL.fullmatch(sender) or not recipients or not all(EMAIL.fullmatch(r) for r in recipients):
            raise ConfigError('GF_SMTP_FROM_ADDRESS and ALERT_EMAIL_TO must be email addresses')
        name = env.get('GF_SMTP_FROM_NAME', 'Krate').replace('"', '')
        lines += [
            'global:',
            '  smtp_smarthost: %s' % yaml_string(smarthost),
            '  smtp_from: %s' % yaml_string('%s <%s>' % (name, sender) if name else sender),
            '  smtp_require_tls: %s' % ('true' if flag(env, 'ALERTMANAGER_SMTP_REQUIRE_TLS', True) else 'false'),
            '  smtp_tls_config:',
            '    insecure_skip_verify: %s' % ('true' if flag(env, 'GF_SMTP_SKIP_VERIFY') else 'false'),
        ]
        if env.get('GF_SMTP_USER'):
            lines += ['  smtp_auth_username: %s' % yaml_string(env['GF_SMTP_USER']),
                      '  smtp_auth_password_file: /etc/alertmanager/rendered/smtp-password']
    # Same grouping and timing as the Grafana notification rules.
    lines += [
        'route:',
        '  receiver: %s' % ('krate-email' if enabled else 'krate-none'),
        '  group_by: [alertname]',
        '  group_wait: 10s',
        '  group_interval: 5m',
        '  repeat_interval: 4h',
        'receivers:',
        '  - name: krate-none',
    ]
    if enabled:
        lines += [
            '  - name: krate-email',
            '    email_configs:',
            '      - to: %s' % yaml_string(', '.join(recipients)),
            '        send_resolved: true',
        ]
    return '\n'.join(lines) + '\n'


def write(path, content, uid, mode=0o400):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name('.' + path.name + '.tmp')
    temporary.write_text(content)
    os.chown(temporary, uid, uid)
    os.chmod(temporary, mode)
    os.replace(temporary, path)


def clear(directory):
    """Empty a directory and leave it writable for rendering."""
    directory.mkdir(parents=True, exist_ok=True)
    os.chmod(directory, 0o700)
    for child in directory.iterdir():
        if child.is_dir() and not child.is_symlink():
            os.chmod(child, 0o700)
            shutil.rmtree(child)
        else:
            child.unlink()


def seal(directory, uid):
    """Hand a rendered directory tree to its reader, read-only."""
    for path in sorted(directory.rglob('*'), reverse=True):
        if path.is_dir():
            os.chown(path, uid, uid)
            os.chmod(path, 0o500)
    os.chown(directory, uid, uid)
    os.chmod(directory, 0o500)


def render(env, out, site_path):
    mode = env.get('PERSES_AUTH_MODE', 'local')
    if mode not in ('local', 'native', 'gateway'):
        raise ConfigError('PERSES_AUTH_MODE must be local, native or gateway')
    key = require(env, 'PERSES_ENCRYPTION_KEY')
    if len(key.encode()) != 32:
        raise ConfigError('PERSES_ENCRYPTION_KEY must be exactly 32 bytes')
    site = site_settings(site_path, mode) if mode != 'local' else {}
    if mode != 'local':
        require(env, 'OAUTH2_PROXY_COOKIE_SECRET')
        require(env, 'OAUTH2_PROXY_CLIENT_SECRET')
    outputs = {
        'perses': (PERSES_UID, {
            'config.yaml': perses_config(mode, site),
            'encryption.key': key,
            'provisioning/site.json': json.dumps(perses_provisioning(mode, env, site), indent=2) + '\n',
        }),
        'gateway': (0, {'default.conf': gateway_config(mode, env)}),
        'alertmanager': (ALERTMANAGER_UID, {'alertmanager.yml': alertmanager_config(env)}),
    }
    if env.get('GF_SMTP_USER') and flag(env, 'ALERTMANAGER_EMAIL_ENABLED', flag(env, 'GF_SMTP_ENABLED')):
        outputs['alertmanager'][1]['smtp-password'] = env.get('GF_SMTP_PASSWORD', '')
    if mode == 'native':
        outputs['perses'][1]['oidc-client-secret'] = require(env, 'OAUTH2_PROXY_CLIENT_SECRET')
    if mode != 'local':
        outputs['oauth2-proxy'] = (PERSES_UID, {'oauth2-proxy.cfg': oauth2_proxy_config(site, env)})
        sync = {'config.json': sync_config(mode, site)}
        if mode == 'native':
            sync['service-client-secret'] = require(env, 'PERSES_SYNC_CLIENT_SECRET')
        outputs['perses-sync'] = (SYNC_UID, sync)
    # Validate everything before touching any output volume.
    for name, (uid, files) in outputs.items():
        target = out / name
        clear(target)
        for relative, content in files.items():
            write(target / relative, content, uid)
        seal(target, uid)
    for name in ('oauth2-proxy', 'perses-sync'):
        if name not in outputs and (out / name).exists():
            clear(out / name)
            seal(out / name, 0)
    # Writable state for the non-root guard and seed helpers.
    for name in ('perses-sync', 'perses-seed'):
        state = out / 'state' / name
        if state.is_dir():
            os.chown(state, SYNC_UID, SYNC_UID)
            os.chmod(state, 0o700)
    return mode


def main():
    out = Path(sys.argv[1] if len(sys.argv) > 1 else '/rendered')
    site = sys.argv[2] if len(sys.argv) > 2 else '/etc/krate/site/perses.json'
    try:
        mode = render(dict(os.environ), out, site)
    except ConfigError as exc:
        print('monitoring-init: ' + str(exc), file=sys.stderr)
        return 1
    print('monitoring-init: rendered %s mode configuration' % mode)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
